all: hello.o mello.o

hello.o: 
	gcc hello.c -o ../src/hello.o 
	gcc hello.c -o ../test/hello.o

mello.o:
	gcc mello.c -o ../src/mello.o
	gcc mello.c -o ../test/mello.o        
        
clean:
	rm *.o
